### ISSUE TITLE
Install certs during deployment

### ISSUE THREAD

**Issue by scriptxyz** [MallocArray/Unifi-OracleCloud#8]
Hi,

Thanks for creating this code.

Is it possible to add one more step that will install let's encrypt certificate during deployment? And also add a script to renew the certificate every a few month

**Comment by MallocArray** [comment]
That was certainly the goal and the script that I used to base this terraform file from supported that, but looks like certbot was depreciated so some additional work is needed to update it to current methods and I haven't had time to work on it.

If you have a shell script that can handle the steps I can work on adding those to the script that runs at first boot.  Otherwise, I hope to get to it some day, but probably not soon.

**Comment by MallocArray** [comment]
I am actively working on updating this to use the Easy install script from Glenn R which supports Lets Encrypt on install and I plan to add a scheduled task to update the application and certs.  So hopefully some good progress soon.

**Comment by MallocArray** [comment]
This is supported now, as the Easy Install Script that is called fully supports Lets Encrypt
